import { Container } from 'inversify';
import { repositories, useCases } from './symbols';

// Import implementations
import type { ContentRepository } from '@/_core/modules/content/infrastructure/repositories/ContentRepository';
import type { CourseRepository } from '@/_core/modules/content/infrastructure/repositories/CourseRepository';
import type { CourseTutorRepository } from '@/_core/modules/content/infrastructure/repositories/CourseTutorRepository';
import type { ModuleRepository } from '@/_core/modules/content/infrastructure/repositories/ModuleRepository';
import type { LessonRepository } from '@/_core/modules/content/infrastructure/repositories/LessonRepository';
import type { ActivityRepository } from '@/_core/modules/content/infrastructure/repositories/ActivityRepository';
import type { ActivitySubmissionRepository } from '@/_core/modules/content/infrastructure/repositories/ActivitySubmissionRepository';
import type { QuestionnaireRepository } from '@/_core/modules/content/infrastructure/repositories/QuestionnaireRepository';
import type { QuestionnaireSubmissionRepository } from '@/_core/modules/content/infrastructure/repositories/QuestionnaireSubmissionRepository';
import type { LessonProgressRepository } from '@/_core/modules/content/infrastructure/repositories/LessonProgressRepository';
import type { TrailRepository } from '@/_core/modules/content/infrastructure/repositories/TrailRepository';
import type { IScormContentClientRepository } from '@/_core/modules/content/infrastructure/repositories/ScormContentClientRepository';
import { FirebaseContentRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseContentRepository';
import { FirebaseCourseRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseCourseRepository';
import { FirebaseCourseTutorRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseCourseTutorRepository';
import { FirebaseModuleRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseModuleRepository';
import { FirebaseLessonRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseLessonRepository';
import { FirebaseActivityRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseActivityRepository';
import { FirebaseActivitySubmissionRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseActivitySubmissionRepository';
import { FirebaseQuestionnaireRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseQuestionnaireRepository';
import { FirebaseQuestionnaireSubmissionRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseQuestionnaireSubmissionRepository';
import { FirebaseLessonProgressRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseLessonProgressRepository';
import { FirebaseTrailRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/FirebaseTrailRepository';
import { ScormContentAPIRepository } from '@/_core/modules/content/infrastructure/repositories/implementations/ScormContentAPIRepository';
import { CreateContentUseCase } from '@/_core/modules/content/core/use-cases/create-content/create-content.use-case';
import { CreateCourseUseCase } from '@/_core/modules/content/core/use-cases/create-course/create-course.use-case';
import { UpdateCourseUseCase } from '@/_core/modules/content/core/use-cases/update-course/update-course.use-case';
import { CreateModuleUseCase } from '@/_core/modules/content/core/use-cases/create-module/create-module.use-case';
import { CreateLessonUseCase } from '@/_core/modules/content/core/use-cases/create-lesson/create-lesson.use-case';
import { AddContentToLessonUseCase } from '@/_core/modules/content/core/use-cases/add-content-to-lesson/add-content-to-lesson.use-case';
import { CreateActivityUseCase } from '@/_core/modules/content/core/use-cases/create-activity/create-activity.use-case';
import { CreateQuestionnaireUseCase } from '@/_core/modules/content/core/use-cases/create-questionnaire/create-questionnaire.use-case';
import { AddQuestionToQuestionnaireUseCase } from '@/_core/modules/content/core/use-cases/add-question-to-questionnaire/add-question-to-questionnaire.use-case';
import { UpdateQuestionUseCase } from '@/_core/modules/content/core/use-cases/update-question/update-question.use-case';
import { DeleteQuestionUseCase } from '@/_core/modules/content/core/use-cases/delete-question/delete-question.use-case';
import { ListQuestionsOfQuestionnaireUseCase } from '@/_core/modules/content/core/use-cases/list-questions-of-questionnaire/list-questions-of-questionnaire.use-case';
import { SubmitQuestionnaireUseCase } from '@/_core/modules/content/core/use-cases/submit-questionnaire/submit-questionnaire.use-case';
import { RetryQuestionnaireUseCase } from '@/_core/modules/content/core/use-cases/retry-questionnaire/retry-questionnaire.use-case';
import { AssociateTutorToCourseUseCase } from '@/_core/modules/content/core/use-cases/associate-tutor-to-course/associate-tutor-to-course.use-case';
import { ListTutorCoursesUseCase } from '@/_core/modules/content/core/use-cases/list-tutor-courses';
import { ListTutorCoursesWithStudentsUseCase } from '@/_core/modules/content/core/use-cases/list-tutor-courses-with-students';
import { ListCoursesByInstitutionUseCase } from '@/_core/modules/content/core/use-cases/list-courses-by-institution';
import { ListQuestionnaireSubmissionsForTutorUseCase } from '@/_core/modules/content/core/use-cases/list-questionnaire-submissions-for-tutor';
import { StartLessonProgressUseCase } from '@/_core/modules/content/core/use-cases/start-lesson-progress/start-lesson-progress.use-case';
import { UpdateContentProgressUseCase } from '@/_core/modules/content/core/use-cases/update-content-progress/update-content-progress.use-case';
import { GetLessonProgressUseCase } from '@/_core/modules/content/core/use-cases/get-lesson-progress/get-lesson-progress.use-case';
import { CompleteLessonProgressUseCase } from '@/_core/modules/content/core/use-cases/complete-lesson-progress/complete-lesson-progress.use-case';
import { CanAccessLessonUseCase } from '@/_core/modules/content/core/use-cases/can-access-lesson/can-access-lesson.use-case';
import { CreateTrailUseCase } from '@/_core/modules/content/core/use-cases/create-trail/create-trail.use-case';
import { UpdateTrailUseCase } from '@/_core/modules/content/core/use-cases/update-trail/update-trail.use-case';
import { GetTrailUseCase } from '@/_core/modules/content/core/use-cases/get-trail/get-trail.use-case';
import { ListTrailsUseCase } from '@/_core/modules/content/core/use-cases/list-trails/list-trails.use-case';
import { DeleteTrailUseCase } from '@/_core/modules/content/core/use-cases/delete-trail/delete-trail.use-case';
import { AddCourseToTrailUseCase } from '@/_core/modules/content/core/use-cases/add-course-to-trail/add-course-to-trail.use-case';
import { RemoveCourseFromTrailUseCase } from '@/_core/modules/content/core/use-cases/remove-course-from-trail/remove-course-from-trail.use-case';
import { UpdateLessonDescriptionUseCase } from '@/_core/modules/content/core/use-cases/update-lesson-description/update-lesson-description.use-case';
import { RemoveContentFromLessonUseCase } from '@/_core/modules/content/core/use-cases/remove-content-from-lesson/remove-content-from-lesson.use-case';
import { UploadActivityFilesUseCase } from '@/_core/modules/content/core/use-cases/upload-activity-files/upload-activity-files.use-case';
import { ListActivityFilesUseCase } from '@/_core/modules/content/core/use-cases/list-activity-files/list-activity-files.use-case';
import { DeleteActivityFileUseCase } from '@/_core/modules/content/core/use-cases/delete-activity-file/delete-activity-file.use-case';
import { ApproveRejectActivitySubmissionUseCase } from '@/_core/modules/content/core/use-cases/approve-reject-activity-submission';
import { GetCourseProgressUseCase } from '@/_core/modules/content/core/use-cases/get-course-progress';
import { UploadPdfToLessonUseCase } from '@/_core/modules/content/core/use-cases/upload-pdf-to-lesson/upload-pdf-to-lesson.use-case';
import { DeletePdfFromLessonUseCase } from '@/_core/modules/content/core/use-cases/delete-pdf-from-lesson/delete-pdf-from-lesson.use-case';
import { UploadMp3ToLessonUseCase } from '@/_core/modules/content/core/use-cases/upload-mp3-to-lesson/upload-mp3-to-lesson.use-case';
// import { ListContentsUseCase } from '@/_core/modules/content/core/use-cases/list-contents/list-contents.use-case';

/**
 * Register Content module dependencies
 * @param container The DI container
 */
export function registerContentModule(container: Container): void {
  // Register repositories
  container.bind<ContentRepository>(repositories.ContentRepository).to(FirebaseContentRepository);
  container.bind<CourseRepository>(repositories.CourseRepository).to(FirebaseCourseRepository);
  container.bind<CourseTutorRepository>(repositories.CourseTutorRepository).to(FirebaseCourseTutorRepository);
  container.bind<ModuleRepository>(repositories.ModuleRepository).to(FirebaseModuleRepository);
  container.bind<LessonRepository>(repositories.LessonRepository).to(FirebaseLessonRepository);
  container.bind<ActivityRepository>(repositories.ActivityRepository).to(FirebaseActivityRepository);
  container.bind<ActivitySubmissionRepository>(repositories.ActivitySubmissionRepository).to(FirebaseActivitySubmissionRepository);
  container.bind<QuestionnaireRepository>(repositories.QuestionnaireRepository).to(FirebaseQuestionnaireRepository);
  container.bind<QuestionnaireSubmissionRepository>(repositories.QuestionnaireSubmissionRepository).to(FirebaseQuestionnaireSubmissionRepository);
  container.bind<LessonProgressRepository>(repositories.LessonProgressRepository).to(FirebaseLessonProgressRepository);
  container.bind<TrailRepository>(repositories.TrailRepository).to(FirebaseTrailRepository);
  container.bind<IScormContentClientRepository>(repositories.ScormContentClientRepository).to(ScormContentAPIRepository);
  
  // Register use cases
  container.bind(useCases.CreateContentUseCase).to(CreateContentUseCase);
  container.bind(useCases.CreateCourseUseCase).to(CreateCourseUseCase);
  container.bind(useCases.UpdateCourseUseCase).to(UpdateCourseUseCase);
  container.bind(useCases.CreateModuleUseCase).to(CreateModuleUseCase);
  container.bind(useCases.CreateLessonUseCase).to(CreateLessonUseCase);
  container.bind(useCases.AddContentToLessonUseCase).to(AddContentToLessonUseCase);
  container.bind(useCases.CreateActivityUseCase).to(CreateActivityUseCase);
  container.bind(useCases.CreateQuestionnaireUseCase).to(CreateQuestionnaireUseCase);
  container.bind(useCases.AddQuestionToQuestionnaireUseCase).to(AddQuestionToQuestionnaireUseCase);
  container.bind(useCases.UpdateQuestionUseCase).to(UpdateQuestionUseCase);
  container.bind(useCases.DeleteQuestionUseCase).to(DeleteQuestionUseCase);
  container.bind(useCases.ListQuestionsOfQuestionnaireUseCase).to(ListQuestionsOfQuestionnaireUseCase);
  container.bind(useCases.SubmitQuestionnaireUseCase).to(SubmitQuestionnaireUseCase);
  container.bind(useCases.RetryQuestionnaireUseCase).to(RetryQuestionnaireUseCase);
  container.bind(useCases.AssociateTutorToCourseUseCase).to(AssociateTutorToCourseUseCase);
  container.bind(useCases.ListTutorCoursesUseCase).to(ListTutorCoursesUseCase);
  container.bind(useCases.ListTutorCoursesWithStudentsUseCase).to(ListTutorCoursesWithStudentsUseCase);
  container.bind(useCases.ListCoursesByInstitutionUseCase).to(ListCoursesByInstitutionUseCase);
  container.bind(useCases.ListQuestionnaireSubmissionsForTutorUseCase).to(ListQuestionnaireSubmissionsForTutorUseCase);
  container.bind(useCases.StartLessonProgressUseCase).to(StartLessonProgressUseCase);
  container.bind(useCases.UpdateContentProgressUseCase).to(UpdateContentProgressUseCase);
  container.bind(useCases.GetLessonProgressUseCase).to(GetLessonProgressUseCase);
  container.bind(useCases.CompleteLessonProgressUseCase).to(CompleteLessonProgressUseCase);
  container.bind(useCases.CanAccessLessonUseCase).to(CanAccessLessonUseCase);
  container.bind(useCases.CreateTrailUseCase).to(CreateTrailUseCase);
  container.bind(useCases.UpdateTrailUseCase).to(UpdateTrailUseCase);
  container.bind(useCases.GetTrailUseCase).to(GetTrailUseCase);
  container.bind(useCases.ListTrailsUseCase).to(ListTrailsUseCase);
  container.bind(useCases.DeleteTrailUseCase).to(DeleteTrailUseCase);
  container.bind(useCases.AddCourseToTrailUseCase).to(AddCourseToTrailUseCase);
  container.bind(useCases.RemoveCourseFromTrailUseCase).to(RemoveCourseFromTrailUseCase);
  container.bind(useCases.UpdateLessonDescriptionUseCase).to(UpdateLessonDescriptionUseCase);
  container.bind(useCases.RemoveContentFromLessonUseCase).to(RemoveContentFromLessonUseCase);
  container.bind(useCases.UploadActivityFilesUseCase).to(UploadActivityFilesUseCase);
  container.bind(useCases.ListActivityFilesUseCase).to(ListActivityFilesUseCase);
  container.bind(useCases.DeleteActivityFileUseCase).to(DeleteActivityFileUseCase);
  container.bind(useCases.ApproveRejectActivitySubmissionUseCase).to(ApproveRejectActivitySubmissionUseCase);
  container.bind(useCases.GetCourseProgressUseCase).to(GetCourseProgressUseCase);
  container.bind(useCases.UploadPdfToLessonUseCase).to(UploadPdfToLessonUseCase);
  container.bind(useCases.DeletePdfFromLessonUseCase).to(DeletePdfFromLessonUseCase);
  container.bind(useCases.UploadMp3ToLessonUseCase).to(UploadMp3ToLessonUseCase);
  // container.bind(useCases.ListContentsUseCase).to(ListContentsUseCase);
}
